### ISSUE TITLE
dynamique centered background

### ISSUE THREAD

**Issue by Puthus** [iamanas20/Forest-Ranger#3]
so the idea is that the background should be centered and should get resized after the window is bigger than the img resolution the img will stay with the same ration taking whichever bigger dimension relative to the ratio

**Comment by chain-xvi** [comment]
try the fixes in https://stackoverflow.com/questions/21209840/css-how-to-stretch-and-auto-resize-background-image

**Comment by chain-xvi** [comment]
and also check this: https://css-tricks.com/perfect-full-page-background-image/

**Comment by Puthus** [comment]
that'S what i wanted gj
